### ISSUE TITLE
undefined method `empty?' for #<Inspec::Rule:0x00005607e634ae88>

### ISSUE THREAD

**Issue by kidbrax** [dev-sec/ssl-baseline#40]
**Describe the bug**
Fails every time with `undefined method `empty?' for #<Inspec::Rule:0x00005607e634ae88>`

**Expected behavior**
Expect all tests to pass. These passed fine a few days ago.

**Actual behavior**

```
1) Control Source Code Error ssl-baseline-master/controls/ssl_test.rb:92
       Failure/Error: its(location) { fail e.message } # rubocop: disable Style/SignalException
    amazon-ebs:
       RuntimeError:
         undefined method `empty?' for #<Inspec::Rule:0x00005607e634ae88>
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/rule.rb:61:in `block (2 levels) in initialize'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example.rb:262:in `instance_exec'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example.rb:262:in `block in run'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/hooks.rb:486:in `block in run'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/hooks.rb:486:in `run'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example.rb:259:in `run'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example_group.rb:644:in `block in run_examples'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example_group.rb:640:in `map'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example_group.rb:640:in `run_examples'
       # /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example_group.rb:606:in `run'

```

**OS / Environment**

**Inspec Version**

```paste below
    inspec-bin (4.26.4)
      inspec (= 4.26.4)
    inspec-core (4.26.4)
```

**Baseline Version**

```
https://github.com/dev-sec/ssl-baseline/archive/master.tar.gz
```

**Additional context**

`sslports` is set to empty at https://github.com/dev-sec/ssl-baseline/blob/master/controls/ssl_test.rb#L66

And when that variable  is read in each test following, is when the error occurs. It happens for every test in ssl-baseline.
